language: php

php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"

before_script:
  - composer install --prefer-dist --dev

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

script: phpunit --stderr ./tests
